// <auto-generated />
using System;
using CycleTrust.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CycleTrust.Infrastructure.Migrations
{
    [DbContext(typeof(CycleTrustDbContext))]
    [Migration("20260309015242_AddNotificationsAndChat")]
    partial class AddNotificationsAndChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CycleTrust.Core.Entities.BikeCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("bike_categories", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ChatConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("LastMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("last_message");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_message_at");

                    b.Property<long?>("LastMessageSenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_message_sender_id");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<int>("UnreadCountBuyer")
                        .HasColumnType("int")
                        .HasColumnName("unread_count_buyer");

                    b.Property<int>("UnreadCountSeller")
                        .HasColumnType("int")
                        .HasColumnName("unread_count_seller");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ListingId");

                    b.HasIndex("SellerId");

                    b.HasIndex("BuyerId", "SellerId", "ListingId")
                        .IsUnique();

                    b.ToTable("chat_conversations", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SenderId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.DepositPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("FixedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("fixed_amount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<long?>("MaxAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("max_amount");

                    b.Property<long>("MinAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("min_amount");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mode");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<decimal?>("PercentValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percent_value");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("policy_name");

                    b.HasKey("Id");

                    b.ToTable("deposit_policies", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Dispute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_admin_id");

                    b.Property<long?>("AssignedInspectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_inspector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("OpenedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("opened_by");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("longtext")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminId");

                    b.HasIndex("AssignedInspectorId");

                    b.HasIndex("OpenedBy");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.DisputeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("DisputeId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispute_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("DisputeId");

                    b.ToTable("dispute_events", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Inspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("json")
                        .HasColumnName("checklist_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("InspectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspector_id");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<string>("ReportUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("report_url");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InspectorId");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.ToTable("inspections", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Listing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approved_by");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("ConditionNote")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("condition_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LocationText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_text");

                    b.Property<long>("PriceAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("price_amount");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("longtext")
                        .HasColumnName("rejected_reason");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<long?>("SizeOptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("size_option_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageHistory")
                        .HasColumnType("longtext")
                        .HasColumnName("usage_history");

                    b.Property<int?>("YearModel")
                        .HasColumnType("int")
                        .HasColumnName("year_model");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SizeOptionId");

                    b.HasIndex("Status");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ListingMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("listing_media", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("action_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<long?>("RelatedEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("buyer_id");

                    b.Property<string>("CanceledReason")
                        .HasColumnType("longtext")
                        .HasColumnName("canceled_reason");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered_at");

                    b.Property<long>("DepositAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("deposit_amount");

                    b.Property<DateTime?>("DepositDueAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deposit_due_at");

                    b.Property<DateTime?>("DepositPaidAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deposit_paid_at");

                    b.Property<bool>("DepositRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deposit_required");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<long>("PriceAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("price_amount");

                    b.Property<DateTime?>("ReserveExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reserve_expires_at");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<string>("ShippingNote")
                        .HasColumnType("longtext")
                        .HasColumnName("shipping_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ListingId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTxnId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("provider_txn_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("buyer_id");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.SizeOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("size_options", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("approval_status");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<decimal>("RatingAvg")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating_avg");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("rating_count");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ViolationReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<long?>("HandledBy")
                        .HasColumnType("bigint")
                        .HasColumnName("handled_by");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason");

                    b.Property<long?>("ReportedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reported_user_id");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("longtext")
                        .HasColumnName("resolution_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HandledBy");

                    b.HasIndex("ListingId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("Status");

                    b.ToTable("violation_reports", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Wishlist", b =>
                {
                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("buyer_id");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("BuyerId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ChatConversation", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Dispute", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "AssignedAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.User", "AssignedInspector")
                        .WithMany()
                        .HasForeignKey("AssignedInspectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.Order", "Order")
                        .WithOne("Dispute")
                        .HasForeignKey("CycleTrust.Core.Entities.Dispute", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAdmin");

                    b.Navigation("AssignedInspector");

                    b.Navigation("OpenedByUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.DisputeEvent", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.Dispute", "Dispute")
                        .WithMany("Events")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Inspection", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Inspector")
                        .WithMany("Inspections")
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.Listing", "Listing")
                        .WithOne("Inspection")
                        .HasForeignKey("CycleTrust.Core.Entities.Inspection", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspector");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Listing", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.Brand", "Brand")
                        .WithMany("Listings")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.BikeCategory", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.User", "Seller")
                        .WithMany("Listings")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.SizeOption", "SizeOption")
                        .WithMany("Listings")
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Seller");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ListingMedia", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.Listing", "Listing")
                        .WithMany("Media")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Notification", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Order", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Buyer")
                        .WithMany("OrdersAsBuyer")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.Listing", "Listing")
                        .WithMany("Orders")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.User", "Seller")
                        .WithMany("OrdersAsSeller")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Payment", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Review", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Buyer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("CycleTrust.Core.Entities.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.User", "Seller")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Order");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ViolationReport", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Handler")
                        .WithMany()
                        .HasForeignKey("HandledBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CycleTrust.Core.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Handler");

                    b.Navigation("Listing");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Wishlist", b =>
                {
                    b.HasOne("CycleTrust.Core.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CycleTrust.Core.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.BikeCategory", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Brand", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Dispute", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Listing", b =>
                {
                    b.Navigation("Inspection");

                    b.Navigation("Media");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.Order", b =>
                {
                    b.Navigation("Dispute");

                    b.Navigation("Payments");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.SizeOption", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("CycleTrust.Core.Entities.User", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("Listings");

                    b.Navigation("OrdersAsBuyer");

                    b.Navigation("OrdersAsSeller");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
